# base image
FROM node:16-alpine

# set working directory
WORKDIR /app

# Create app folder
COPY package.json .

# install and cache app dependencies
RUN npm install --silent
# RUN npm install react-scripts@3.0.1 -g --silent

COPY . .

# start app
CMD ["npm", "start"]
